name: Render Template

on:
  workflow_dispatch:
    inputs:
      archetect-source:
        description: "Archetype Source Git URL"
        required: true
      archetect-options:
        description: "Archetect Render Options"
        required: false
      github-token:
        description: "A GitHub Token with `repo` and `workflows` permission"
        required: true

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: scaffoldly/archetect-render-action@1.0.3-2
        with:
          source: "${{ github.event.inputs.archetect-source }}"
          options: "${{ github.event.inputs.archetect-options }}"
          github-token: "${{ github.event.inputs.github-token }}"
