name: Render Template

on:
  workflow_dispatch:
    inputs:
      archetect-source:
        description: "Archetype Source Git URL"
        required: true
      archetect-source-gitref:
        description: "Source Git Reference (Branch/Tag/SHA)"
        required: true
      archetect-options:
        description: "Archetect Render Options"
        required: false
      github-token:
        description: "A GitHub Token with `repo` and `workflows` permission"
        required: true

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.event.inputs.github-token }}
      - uses: scaffoldly/archetect-render-action@v1
        with:
          source: "${{ github.event.inputs.archetect-source }}"
          source-gitref: "${{ github.event.inputs.archetect-source-gitref }}"
          options: "${{ github.event.inputs.archetect-options }}"
